global_config = {
    "url": {
        "landing_page": "https://service.rochester.edu/servicedesk/customer/portal/101/create/358?q=lending&q_time=1693601714516",
        "landing_base_url": "service.rochester.edu",
        "google_api_scopes": [
            'https://www.googleapis.com/auth/calendar'
        ],
    },
    "text": {
        "ticket_signature": "This ticket was automatically generated by the Rettner 201 Helpdesk. If you have received this in error, you may contact the desk at rettnberhelpdesk@ur.rochester.edu.",
    },
    "xpath": {
        "customer_element": '//*[@id="react-select-2-input"]',
        "source_element": '//*[@id="react-select-customfield_10808-instance-input"]',
        "description_element": '//*[@id="ak-editor-textarea"]',
        "summary_element": '//*[@id="summary"]',
        "resolve_menu_element": '//*[@id="com.atlassian.servicedesk:workflow-transition-761"]',
        "resolve_menu_submit": '/html/body/section/form',
        "open_ticket_information": '//*[@id="content"]/div/header/div/div/div[2]/div[2]/div/ol/li[3]/a',
        "assign_to_me": '//*id="assign-to-me"',
        "people_module": '//*[@id="peoplemodule-label"]/button/span',
        "transition_bar": '//*[@id="opsbar-transitions_more"]/span',
        "close_button": '//*[@id="action_id_941"]/a/div/div[1]',
        'username': "//*[@id='usernamevis']",
        'password': "//*[@id='password']",
        'login': "//*[@id='log-on']"
    },
    "file": {
        'credentials': '../resources/secrets/credentials.json',
        'pickle': '../resources/secrets/token.pickle',
    },
    "calendar_parameters":  {
        "time_zone": 'America/New_York',
        "location": 'Rettner Hall Room 201',
        "calendar_id": '062010d99253329019c986e3f5d062cf3ae57abc074bfea1328d008158c602ed@group.calendar.google.com',
        "description": 
            """
            You are about to check out a very expensive piece(s) of electronic equipment from AS&E IT. If you fail to abide by the rules below, your borrowing privileges may be revoked and you may be liable for the full replacement cost. You will be asked to sign an agreement regarding the condition of the item(s) upon return.

            1. I will assume full responsibility for the equipment I am checking out.
            2. I will not let anyone else use the equipment while it is checked out to me.
            3. I will not leave said item(s) unattended. I will always put the item(s) in a safe place when not in use.
            4. When not in use I will always carry the item(s) in its provided bag.
            5. I will return the item(s) in the same condition as when it/they were checked out to me. If any damage or loss occurs while checked out to me, I will be responsible for the full repair or replacement costs.
            6. I will personally return the item(s) before the designated date and time below. Strikes, which expire after 6 months, will be issued for lateness or damage. Bans can be issued for severe violations. An accumulation of 3 strikes will result in a temporary ban. Up to 6 hours late will constitute 1 strike and additional strike(s) will be issued for each subsequent 6 hour period.
            7. For loaner laptops, personal data may not be preserved, and will be purged on restart. The data in the Saved Data folder will be saved, and you are responsible for deleting it before returning the computer.
            """
    },
    "gui": {
        "labels": {
            "login": {
                "title": "Login Form",
                "username": "Username",
                "password": "Password",
            },
            "main_page": {
                "calendar_success_message": "Successfully created Google Calendar event.",
                "unfilled_fields_warning_message": "Select at least one action to continue.",
                "file_default_label": "No file selected",
                "open_file_dialog": "Select a File",
                "title": "AutoJIRA",
                "filepicker_label": "Select a File:",
                "browse_file_button": "Browse",
                "submit_button": "Submit",
                "create_ticket_checkbox": "Create Jira Ticket",
                "create_event_checkbox": "Create Calendar Event",
            }          

        }
    }
}